# Uncomment the next line to define a global platform for your project
platform :ios, '8.4'

target 'manskimarketalert' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for manskimarketalert

pod 'Firebase/Messaging'


  target 'manskimarketalertTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Firebase/Messaging'
  end

end
